server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "dc4e4e03d0f0d9bf17cae5b408153afa9a8e3a50079c4674eae831485f3f6c97"
